server:
  port: 9002
feign:
  hystrix:
    enabled: true
spring:
    mvc:
      view:
        prefix: /WEB-INF/views/
        suffix: .jsp
#hystrix的超时时间
hystrix:
    command:
        default:
            execution:
              timeout:
                enabled: true
              isolation:
                    thread:
                        timeoutInMilliseconds: 9000
#ribbon的超时时间
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000
