server:
  port: 9527
spring:
  application:
    name: AIGOU-ZUUL-GATEWAY
zuul:
  routes:
    product: 
        serviceId: aigou-product
        path: /product/**
    common: 
        serviceId: aigou-common
        path: /common/**
  ignored-services: "*"
  #prefix: /services
  #strip-prefix: false
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  eureka:
    enabled: false