server:
  port: 8002
spring:
  application:
    name: AIGOU-PRODUCT
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aigou_test
    username: root
    password: admin
  cache:
    type: REDIS
    cache-names: redis_cache #缓存的名字
    redis:
     time-to-live: 60000  #很重要，缓存的有效时间，以便缓存的过期（单位为毫秒）
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 127.0.0.1 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: root # Redis服务器连接密码（默认为空）
    timeout: 1000 # 连接超时时间（毫秒
    jedis:
      pool:
        max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
mybatis-plus:
  mapper-locations: classpath:cn/itsource/aigou/mapper/*Mapper.xml
  type-aliases-package: cn.itsource.aigou.domain,cn.itsource.aigou.query
