server:
  port: 8001
spring:
  application:
    name: AIGOU-USER
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aigou_test
    username: root
    password: admin
eureka:
  client:
    service-url:
      defaultZone: http://eureka-7001.com:7001/eureka,http://eureka-7002.com:7002/eureka
  instance:
    prefer-ip-address: true #访问地址显示IP
mybatis:
  type-aliases-package: cn.itsource.aigou.domain,cn.itsource.aigou.query