server:
  port: 9528
spring:
  application:
    name: MICROSERVICE-ZUUL-GATEWAY
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: false
zuul:
  routes:
    product.serviceId: aigou-product
    product.path: /product/**
  ignored-services: "*" #一个一个配置microservice-user
  prefix: /services     #加入前缀